---
type: chart
builds:
- image: golang:1.10.0
  commands: |
    mkdir -p $GOPATH/src/sigs.k8s.io/
    ln -s $(pwd) $GOPATH/src/sigs.k8s.io/cluster-api-provider-ssh
    cd /go/src/sigs.k8s.io/cluster-api-provider-ssh
    set +e
    make depend
    set -e
    make
