---
type: chart
builds:
- image: golang:1.10.0
  commands: |
    pwd
    echo $GOPATH
    set +e
    make depend
    make
    set -e
#- image: samsung_cnct/ssh-cluster-controller
#  context: cluster-controller
#  locationOverride: cmd
#- image: samsung_cnct/ssh-machine-controller
#  context: machine-controller
#  locationOverride: cmd
